import type { Order } from "@/types/order";

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    mode: "online",
    type: "delivery",
    status: "preparing",
    customerName: "Rafiq Hossain",
    customerPhone: "01819234567",
    customerAddress: "House 12, Road 3, Nasirabad, Chittagong",
    items: [
      { menuItemId: "1", name: "Mezzban Beef Bhuna", price: 320, quantity: 2, image: "/images/menu/mezzban-bhuna.webp" },
      { menuItemId: "3", name: "Mezbani Dal", price: 120, quantity: 1, image: "/images/menu/mezbani-dal.png" },
      { menuItemId: "7", name: "Borhani", price: 60, quantity: 2, image: "/images/menu/borhani.webp" },
    ],
    total: 880,
    estimatedMinutes: 25,
    acceptedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-002",
    mode: "table",
    type: "table-food",
    status: "pending",
    tableNumber: "T3",
    customerName: "Table 3 Guest",
    items: [
      { menuItemId: "4", name: "Kala Bhuna", price: 380, quantity: 1, image: "/images/menu/kala-bhuna.png" },
      { menuItemId: "5", name: "Aloo Bhorta", price: 80, quantity: 2, image: "/images/menu/aloo-bhorta.png" },
      { menuItemId: "8", name: "Mishti Doi", price: 90, quantity: 2, image: "/images/menu/mishti-doi.png" },
    ],
    note: "Extra spicy kala bhuna please",
    total: 720,
    estimatedMinutes: 10,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-003",
    mode: "table",
    type: "parcel",
    status: "accepted",
    tableNumber: "T7",
    customerName: "Selim Ahmed",
    customerPhone: "01711345678",
    items: [
      { menuItemId: "6", name: "Ilish Paturi", price: 450, quantity: 1, image: "/images/menu/Ilish-Paturi.png" },
      { menuItemId: "2", name: "CTG Style Shutki Bhorta", price: 180, quantity: 1, image: "/images/menu/shutki-bhorta.png" },
    ],
    total: 630,
    estimatedMinutes: 15,
    acceptedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-004",
    mode: "online",
    type: "delivery",
    status: "pending",
    customerName: "Nusrat Jahan",
    customerPhone: "01912456789",
    customerAddress: "Flat 4B, Khulshi Hills, Chittagong",
    items: [
      { menuItemId: "4", name: "Kala Bhuna", price: 380, quantity: 2, image: "/images/menu/kala-bhuna.png" },
      { menuItemId: "7", name: "Borhani", price: 60, quantity: 3, image: "/images/menu/borhani.webp" },
      { menuItemId: "8", name: "Mishti Doi", price: 90, quantity: 2, image: "/images/menu/mishti-doi.png" },
    ],
    note: "Ring the bell twice",
    total: 1120,
    estimatedMinutes: 10,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-005",
    mode: "table",
    type: "table-food",
    status: "ready",
    tableNumber: "T1",
    customerName: "Table 1 Guest",
    items: [
      { menuItemId: "1", name: "Mezzban Beef Bhuna", price: 320, quantity: 3, image: "/images/menu/mezzban-bhuna.webp" },
      { menuItemId: "3", name: "Mezbani Dal", price: 120, quantity: 3, image: "/images/menu/mezbani-dal.png" },
      { menuItemId: "5", name: "Aloo Bhorta", price: 80, quantity: 2, image: "/images/menu/aloo-bhorta.png" },
    ],
    total: 1280,
    estimatedMinutes: 20,
    acceptedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-006",
    mode: "online",
    type: "delivery",
    status: "delivered",
    customerName: "Tariq Mahmud",
    customerPhone: "01615567890",
    customerAddress: "Road 5, Block C, Panchlaish, Chittagong",
    items: [
      { menuItemId: "6", name: "Ilish Paturi", price: 450, quantity: 2, image: "/images/menu/Ilish-Paturi.png" },
      { menuItemId: "8", name: "Mishti Doi", price: 90, quantity: 4, image: "/images/menu/mishti-doi.png" },
    ],
    total: 1260,
    estimatedMinutes: 30,
    acceptedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
  },
];
